// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"StartUpFullScreen","status":true,"description":"フルスクリーンで起動プラグイン","parameters":{"シャットダウン":"   ＥＸＩＴ","フルスクリーンで起動":"フルスクリーンで起動"}},
{"name":"nonStopCharacter","status":true,"description":"","parameters":{}},
{"name":"SaveFileDrawFace","status":true,"description":"セーブファイルのフェイス表示プラグイン","parameters":{"表示行数":"3","マップ名表示":"ON","ゲームタイトル非表示":"ON"}},
{"name":"TitleCommandPosition","status":true,"description":"タイトルコマンドウィンドウの位置を変更します。","parameters":{"Offset X":"0","Offset Y":"45","Width":"240","Background":"2"}},
{"name":"MKR_PlayerMoveForbid","status":true,"description":"(v1.0.5) プレイヤー移動禁止プラグイン","parameters":{"Default_Move_Flag":"29","Default_Menu_Flag":"true","Enter Flag":"true"}},
{"name":"TerraxLighting","status":true,"description":"v1.5.1 Creates an extra layer that darkens a map and adds lightsources!","parameters":{"Player radius":"250","Add to options":"Yes","Option menu entry":"Lighting effects","Reset Lights":"No","Save DaynightHours":"0","Save DaynightMinutes":"0","Save DaynightSeconds":"0","Flashlight offset":"0","Screensize X":"866","Screensize Y":"630","Kill Switch":"No"}},
{"name":"DisableFastForward","status":true,"description":"イベント高速化禁止プラグイン","parameters":{}},
{"name":"StepSpeed","status":true,"description":"ver1.00/イベントの足踏み速度を変更します。","parameters":{}},
{"name":"SmartPath","status":true,"description":"イベントもしくはプレイヤーに、高度な経路探索を提供します。","parameters":{}},
{"name":"BB_WindowSelector3","status":true,"description":"ウインドウスキンと切り替えるプラグイン。","parameters":{"Variable ID":"189","Window1 Opacity":"255","Window2 Opacity":"255","Window3 Opacity":"192","Window1 OutlineColor":"rgba(0, 0, 0, 0.5)","Window1 OutlineWidth":"4","Window2 OutlineColor":"rgba(0, 0, 0, 0.5)","Window2 OutlineWidth":"4","Window3 OutlineColor":"rgba(0, 0, 0, 0.5)","Window3 OutlineWidth":"4","Window1 DimmerColor":"rgba(0, 0, 0, 0.6)","Window1 DimGradationColor":"rgba(0, 0, 0, 0)","Window2 DimmerColor":"rgba(0, 0, 0, 0.6)","Window2 DimGradationColor":"rgba(0, 0, 0, 0)","Window3 DimmerColor":"rgba(0, 0, 0, 0.6)","Window3 DimGradationColor":"rgba(0, 0, 0, 0)"}},
{"name":"SystemSoundCustomize","status":true,"description":"システム効果音変更プラグイン","parameters":{}},
{"name":"111_InputForm","status":true,"description":"フォーム作って文字入力（修正版）","parameters":{}},
{"name":"TkoolMV_PluginCommandBook","status":true,"description":"プラグインコマンド集","parameters":{"制御文字の拡張":"はい","スクリプトに制御文字適用":"はい"}},
{"name":"CRTA_TimerManager","status":true,"description":"v1.1.0 タイマー関係の管理プラグイン","parameters":{"Font Size":"32","Width":"96","Height":"48","Position X":"680","Position Y":"0"}}
];
